### ISSUE TITLE
Expert Ui can't load, while the engine is up and running

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/ExpertUI#133] opened 2015-08-20 08:13 UTC
After logging in the smarthome UI, the expert UI can't be loaded.
Though the Z-Wave engine is up and running and the devices work ok.
![error_1](https://cloud.githubusercontent.com/assets/5468659/9378713/4bfe1ef6-472c-11e5-89a2-978be12170d9.png)

![error_2](https://cloud.githubusercontent.com/assets/5468659/9378717/544b9c00-472c-11e5-82f7-5377e2ecd750.png)

SyntaxError: Unexpected token a
    at Object.parse (native)
    at fromJson (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:1072:14)
    at defaults.defaults.transformResponse (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:7051:18)
    at http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:7026:12
    at Array.forEach (native)
    at forEach (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:322:11)
    at transformData (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:7025:3)
    at transformResponse (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:7697:17)
    at deferred.promise.then.wrappedCallback (http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:11046:81)
    at http://81.211.107.210:8083/expert/app/vendor/angular/angular-1.2.14/angular.js:11132:26

**Comment by vades** [comment] 2015-10-16 07:03
Unexpected token "a" is usually caused by error in JSON dataholder, lang file etc. 
In your case, it is difficult to determine from where the error comes.

**Comment by PoltoS** [comment] 2015-10-16 08:15
@nilsbohr can you reproduce?

**Comment by NilsBohr** [comment] 2015-10-16 09:09
That's the "NaN" problem. I think it was fixed. Can check on new versions

**Comment by PoltoS** [comment] 2015-10-16 12:08
ah, correct.

**Comment by PoltoS** [comment] 2015-10-16 12:09
Fixed in the backend (in Z-Wave C->JS engine)

**Closed by PoltoS** 2015-10-16 12:08 UTC
Labels: help wanted
