### ISSUE TITLE
On new device added the list of devices in Config is not always updated

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#160] opened 2015-12-10 11:20 UTC
Same happens if you add, remove and add again. The list will contain previous exclused device but not new

**Comment by vades** [comment] 2016-06-14 11:26
Seems to be duplicate of https://github.com/Z-Wave-Me/ExpertUI/issues/178

**Closed** 2016-12-28 10:29 UTC
Labels: bug, duplicate
