### ISSUE TITLE
Thermostats still not works

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#230] opened 2017-02-02 09:30 UTC
Where is buttons to set temperature?
<img width="1280" alt="2017-02-02 12 29 47" src="https://cloud.githubusercontent.com/assets/2894860/22543845/62915790-e943-11e6-848f-a6d581f27968.png">

**Comment by vades** [comment] 2017-03-13 13:26
Duplicate of: https://github.com/Z-Wave-Me/ExpertUI/issues/146

**Closed** 2017-03-13 13:27 UTC
Labels: duplicate
